Repository Unidata/siphon, pull requests merged in 2018-02, with the labels that each got.

#183 Fix build
  .codeclimate.yml
  .gitignore
  environment.yml
  setup.cfg
  setup.py
Labels: Area: Infrastructure, Type: Maintenance

#187 BUG: Fix error path in HTTPEndPoint
  siphon/http_util.py
  siphon/tests/fixtures/gfs-error-no-header
  siphon/tests/test_http_util.py
Labels: Area: Infrastructure, Type: Bug

#188 BUG: Fix embedded metadata elements
  siphon/metadata.py
  siphon/tests/fixtures/ncei_embedded_metadata
  siphon/tests/test_catalog.py
  siphon/tests/test_metadata.py
Labels: Area: Catalog, Type: Bug
