Repository Unidata/siphon, pull requests merged in 2024-11, with the labels that each got.

#804 Update CI testing
  .codecov.yml
  .github/workflows/tests-conda.yml
  .github/workflows/tests-pypi.yml
  ci/Minimum
  ci/doc_requirements.txt
  ci/extra_requirements.txt
  ci/requirements.txt
  ci/test_requirements.txt
  pyproject.toml
  setup.cfg
  src/siphon/_version.py
  src/siphon/cdmr/cdmrfeature_pb2.py
  src/siphon/cdmr/ncStream_pb2.py
Labels: Type: Maintenance, Area: Infrastructure, Type: Enhancement

#806 Update release workflow
  .github/workflows/release.yml
Labels: Type: Maintenance, Area: Infrastructure

#805 Drop in MetPy docs workflow
  .github/workflows/docs-conda.yml
  .github/workflows/docs.yml
  ci/doc_requirements.txt
  ci/download_cartopy_maps.py
  ci/filter_links.py
  docs/conf.py
  docs/index.rst
  environment.yml
  pyproject.toml
Labels: Type: Maintenance, Area: Infrastructure, Type: Enhancement

#811 Bump protobuf to 5.28.2
  ci/requirements.txt
Labels: Type: Maintenance

#827 Add workflows for unstable dependencies
  .github/workflows/nightly-builds.yml
  .github/workflows/run-unstable-pr.yml
  .github/workflows/unstable-builds.yml
Labels: Area: Infrastructure, Type: Enhancement

#830 Miscellaneous Cleanups
  .gitignore
  CONTRIBUTING.md
  README.rst
  TODO.md
  docs/conf.py
  docs/developerguide.rst
  examples/Radar_Server_Level_3.py
  examples/ncss/NCSS_Cartopy_Example.py
  examples/ncss/NCSS_Example.py
  examples/ncss/NCSS_Timeseries_Examples.py
  pyproject.toml
  src/siphon/catalog.py
  src/siphon/http_util.py
  src/siphon/ncss.py
  src/siphon/radarserver.py
  src/siphon/simplewebservice/acis.py
  src/siphon/simplewebservice/iastate.py
  src/siphon/simplewebservice/igra2.py
  src/siphon/simplewebservice/ndbc.py
  src/siphon/simplewebservice/wyoming.py
  tests/test_catalog.py
  tests/test_http_util.py
  tests/test_igra2.py
Labels: Type: Maintenance

#831 Python 3.13
  .github/workflows/docs-conda.yml
  .github/workflows/docs.yml
  .github/workflows/tests-conda.yml
  .github/workflows/tests-pypi.yml
  pyproject.toml
Labels: Area: Infrastructure, Type: Enhancement

#840 Update dependabot & nightly workflows
  .github/dependabot.yml
  .github/workflows/automerge-dependabot.yml
  .github/workflows/nightly-builds.yml
Labels: Type: Maintenance, Area: Infrastructure
